name: GitHub Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_languages: yes
          plugin_languages_ignored: jupyter-notebook, html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          
          plugin_habits: yes
          plugin_habits_from: 600       # Use 600 events to compute habits
          plugin_habits_days: 300       # Keep only events from last 300 days
          plugin_habits_facts: yes      # Display facts section
